### ISSUE TITLE
Animation only works if previous animation has finished (and had time to reset?)

### ISSUE THREAD

**Issue by MossP** [joeyschroeder/react-native-animated-background-color-view#2]
Linked with https://github.com/joeyschroeder/react-native-animated-background-color-view/issues/1

The animation appears to only work if the previous animation has completed and had a period of time to reset. If a new animation is triggered within that timeframe the queued animation transitions immediately to the newly requested colour.

**Comment by joeyschroeder** [comment]
Hey @MossP I was actually just about to respond to your comment earlier. I'll see if i can get this resolved.  Thanks for your help on narrowing down the issue.

**Comment by MossP** [comment]
Hey @joeyschroeder, no probs. Me opening a new ticket wasn't mean't as a hurry along. I thought it wise to open a new one once I realised I could add more detail to it. :)

**Comment by joeyschroeder** [comment]
Hey, @MossP. I made some updates and pushed a beta version to fix it if you'd like to test: https://www.npmjs.com/package/react-native-animated-background-color-view/v/1.2.0 

In this beta version, when `this.props.color` changes the current animation stops and and interpreted color mixed from the animation stop value and the previous color is set as the start animation color.  A new animation then fires transitioning from this mixed color to the new color prop.

Let me know if you notice anything odd about it.  I appreciate your help in narrowing down this issue.

**Comment by MossP** [comment]
Hi @joeyschroeder.

No probs. I don't mind taking a look at that. I should have a little time tomorrow to check it out.

**Comment by joeyschroeder** [comment]
I ended up publishing version 1.2.1: https://www.npmjs.com/package/react-native-animated-background-color-view/v/1.2.1, I felt pretty confident in the fix.  But feel free to log any more bugs if you see something wonky.  Thanks again for your help!

**Comment by MossP** [comment]
Sorry for the delay. I’ll try to test this over the weekend. Had a busy week, apologies.

**Comment by joeyschroeder** [comment]
@MossP no problemo! It's all good 😎
