### ISSUE TITLE
Invalid container style

### ISSUE THREAD

**Issue by outaTiME** [joeyschroeder/react-native-animated-background-color-view#4]
Hi, 
To work like standard view the container style should remove the flex attribute in the following line:

https://github.com/joeyschroeder/react-native-animated-background-color-view/blob/master/src/animated-background-color-view/animated-background-color-view.component.js#L9

For now my workaround is override flex value with my custom style using `flex: 0`, 

Thanks !!!

**Comment by joeyschroeder** [comment]
Hey @outaTiME, just so I understand the request, are you saying I could just drop that style entirely from the container?  Thanks for helping out!

**Comment by outaTiME** [comment]
@joeyschroeder if you like to work as standard view yes

**Comment by joeyschroeder** [comment]
@outaTiME, sure that makes sense. I'll get it fixed and push out an update..

**Comment by outaTiME** [comment]
Great, thanks 🙏

**Comment by joeyschroeder** [comment]
@outaTiME a new release has been pushed out with this update. The default style is no longer `{ flex: 1 }`.  It should now match the default `<View />` styles.

https://www.npmjs.com/package/react-native-animated-background-color-view/v/1.3.0

**Comment by outaTiME** [comment]
Awesome @joeyschroeder, thanks !!!
