### ISSUE TITLE
useNativeDriver warning

### ISSUE THREAD

**Issue by Mohammad-SS** [joeyschroeder/react-native-animated-background-color-view#6]
Hi , im using : 
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-animated-background-color-view": "^1.3.0",
and whenever i call AnimatedBackgroundColorView , i see this warning :
![Screenshot_1592812514](https://user-images.githubusercontent.com/20665984/85262744-741d1580-b483-11ea-93c0-01d1948e51de.png) .

**Comment by joeyschroeder** [comment]
I apologize for the slow response.  This issue was fixed in the latest version.  Thanks! 🙂
